swagger: '2.0'
info:
  version: ''
  title: SOTA Device Registry
  description: 'https://github.com/advancedtelematic/rvi_sota_server'
  license:
    name: Mozilla Public License
    url: 'https://github.com/advancedtelematic/rvi_sota_server/blob/master/LICENSE'
host: 'localhost:8083'
basePath: /api/v1
securityDefinitions: {}
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /devices:
    get:
      description: 'Get a list of all the devices in a particular namespace in the device registry.'
      parameters:
      - name: namespace
        in: query
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
    post:
      description: 'Register a new device with a name and an ID, get back its UUID'
      parameters:
      - name: namespace
        in: query
        required: true
        type: string
      - name: DeviceT
        in: body
        required: true
        schema:
          $ref: '#/definitions/DeviceT'
      responses:
        201:
          description: Created - The UUID of the newly-created device
        
  /devices/{uuid}:
    get:
      description: Get the device object for a single device
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Device'
    delete:
      description: Delete a device
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
  /devices/{uuid}/ping:
    post:
      description: Update the last seen time for a device
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
  /devices/{uuid}/system_info:
    post:
      description: Create the system info for a device
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      - name: system
        description: The json object representing the system info
        in: body
        required: true
        schema:
          $ref: '#/definitions/SystemInfo'
      responses:
        201:
          description: Created
    put:
      description: Update the system info for a device
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      - name: system
        description: The json object representing the system info
        in: body
        required: true
        schema:
          $ref: '#/definitions/SystemInfo'
      responses:
        200:
          description: OK
    get:
      description: Retrieve the system info for a device
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/SystemInfo'
  /devices/group_info:
    get:
      description: Returns a list of all groups
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/GroupInfo'
  /devices/{uuid}/group_info:
    post:
      description: Create a group info entry for a namespace/groupName entry
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      - name: groupName
        description: The name of the group of devices
        in: query
        required: true
        type: string
      - name: groupInfo
        description: The json object representing the group info
        in: body
        required: true
        schema:
          $ref: '#/definitions/GroupInfo'
      responses:
        201:
          description: Created
    put:
      description: Update the group info entry for a namespace/groupName entry
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      - name: groupName
        description: The name of the group of devices
        in: query
        required: true
        type: string
      - name: groupInfo
        description: The json object representing the group info
        in: body
        required: true
        schema:
          $ref: '#/definitions/GroupInfo'
      responses:
        200:
          description: OK
    get:
      description: Retrieve the group info for a namespace/groupName entry
      parameters:
      - name: uuid
        description: The uuid of an existing device object
        in: path
        required: true
        type: string
      - name: groupName
        description: The name of the group of devices
        in: query
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GroupInfo'
  /devices/{uuid}/group_info/rename:
    put:
      description: Rename a group
      parameters:
      - name: uuid
        description: The uuid of an existing group
        in: path
        required: true
        type: string
      - name: groupName
        description: The new name of the group
        in: query
        required: true
        type: string
      responses:
        200:
          description: OK
  /device_groups/from_attributes:
    post:
      description: Create a group from two devices' common attributes
      parameters:
      - name: CreateGroupRequest
        description: The group name and devices to compare
        in: body
        required: true
        schema:
          $ref: '#/definitions/CreateGroupRequest'
      responses:
        200:
          description: OK

definitions:
  uuid:
    type: string
    description: 32 lowercase hexadecimal digits, displayed in five groups separated by hyphens
  DeviceId:
    type: string
    description: A 17-digit VIN. May contain only capital letters and digits. Cannot contain the letters I, O, or Q.
  DeviceName:
    type: string
    description: Custom name for a device
  DeviceType:
    type: string
    description: Valid values are "Vehicle" and "Other"
  namespace:
    type: string
    description: The namespace scope of the request. Default value is 'default'
  DeviceT:
    type: object
    properties:
      deviceName:
        $ref: '#/definitions/DeviceName'
      deviceId:
        $ref: '#/definitions/DeviceId'
      deviceType:
        $ref: '#/definitions/DeviceType'
  Device:
    type: object
    properties:
      namespace:
        $ref: '#/definitions/namespace'
      deviceId:
        $ref: '#/definitions/DeviceId'
      id:
        $ref: '#/definitions/uuid'
      deviceName:
        $ref: '#/definitions/DeviceName'
      deviceType:
        $ref: '#/definitions/DeviceType'
      lastseen:
        type: string
        format: dateTime
        description: The last time a device uuid was seen by the SOTA server.
  SystemInfo:
    type: object
    description: A json object representing system info. No schema yet defined.
  GroupInfo:
    type: object
    description: A json object representing device group info. No schema yet defined.
  CreateGroupRequest:
    type: object
    properties:
      device1:
        $ref: '#/definitions/uuid'
      device2:
        $ref: '#/definitions/uuid'
      groupName:
        type: string
        description: a group name between 1 and 100 characters long
