---
layout: page
title: "Contributing"
category: doc
date: 2015-08-26 10:41:08
order: 6
---
:icons: font

This project is developed entirely in the open, on public mailing lists
and with public code reviews. To participate in development discussions, please subscribe to the
https://lists.linuxfoundation.org/mailman/listinfo/automotive-eg-rvi[automotive-eg-rvi]
mailing list, or join the #automotive channel on Freenode. Code is
reviewed on https://gerrithub.io[gerrit]. Development is planned and
issues are tracked in https://www.atlassian.com/software/jira[JIRA].

All code contributed to this project must be licensed under the
https://www.mozilla.org/MPL/2.0/[MPL v2 license], a copy of which you
can find in this repository. Documentation must be licensed under the
https://creativecommons.org/licenses/by/4.0/[CC BY 4.0 license].

[[development-process]]
=== Development Process

This project is developed with a special focus on secure engineering. In
the _docs_ folder you will find details of the security architecture and
threat model.

During development, any interaction between components must be
documented and included in the security modelling. To this end, each
project includes a list of implemented requirements and permitted
interactions.

Developers must only implement functionality for which there is an
associated requirement, described in the project JIRA. When implementing
functionality, developers must update the list of
link:../ref/requirements.html[implemented requirements]. Developers must
only implement interactions that are permitted or whitelisted according
to the associated JIRA ticket. The list of
link:../sec/whitelisted-interactions.html[Whitelisted Interactions]
should be updated when new functionality is implemented, and reviewers
should ensure that the code only implements permitted interactions.
