---
layout: page
title: "Package distribution"
category: cli
date: 2017-04-21 14:15:27
---

= Package distribution to all users of the system

This document describes a script which copies packages uploaded by a
user to the other users of the system. The script queries an LDAP
server to get all the users of the system and then sends a copy
request to the sota core server. The script is meant to be run on a
regular basis, e.g. in a `cron` job.

The script is called `distribute_package.sh` and can be found in the
`deploy` folder of the repository. It can be called as follows:

[source,sh]
----
LDAP_URL=ldap://localhost:389 LDAP_PASSWORD=... CORE_URL=http://localhost:8080 ./distribute_package.sh user packageids...
----

== Required configuration

- LDAP_URL (environment variable): URL of the LDAP server

- LDAP_PASSWORD (environment variable): password of the admin user

- userid (first argument): user from which to copy the packages

- packageids (following arguments): ids of packages to distribute

== Optional configuration

- CORE_URL (environment variable): URL of the sota server, defaults to `http://localhost:8080`.

