(function() {var implementors = {};
implementors["sota"] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='https://doc.rust-lang.org/nightly/collections/borrow/enum.Cow.html' title='collections::borrow::Cow'>Cow</a>&lt;'a,&nbsp;<a class='enum' href='sota/datatype/auth/enum.Auth.html' title='sota::datatype::auth::Auth'>Auth</a>&gt;&gt; for <a class='enum' href='sota/datatype/auth/enum.Auth.html' title='sota::datatype::auth::Auth'>Auth</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='https://doc.rust-lang.org/nightly/collections/borrow/enum.Cow.html' title='collections::borrow::Cow'>Cow</a>&lt;'a,&nbsp;<a class='struct' href='sota/datatype/auth/struct.AccessToken.html' title='sota::datatype::auth::AccessToken'>AccessToken</a>&gt;&gt; for <a class='struct' href='sota/datatype/auth/struct.AccessToken.html' title='sota::datatype::auth::AccessToken'>AccessToken</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='https://doc.rust-lang.org/nightly/collections/borrow/enum.Cow.html' title='collections::borrow::Cow'>Cow</a>&lt;'a,&nbsp;<a class='struct' href='sota/datatype/url/struct.Url.html' title='sota::datatype::url::Url'>Url</a>&gt;&gt; for <a class='struct' href='sota/datatype/url/struct.Url.html' title='sota::datatype::url::Url'>Url</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='https://hyperium.github.io/hyper/hyper/method/enum.Method.html' title='hyper::method::Method'>Method</a>&gt; for <a class='enum' href='sota/datatype/url/enum.Method.html' title='sota::datatype::url::Method'>Method</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='https://doc.rust-lang.org/nightly/collections/borrow/enum.Cow.html' title='collections::borrow::Cow'>Cow</a>&lt;'a,&nbsp;<a class='enum' href='sota/datatype/url/enum.Method.html' title='sota::datatype::url::Method'>Method</a>&gt;&gt; for <a class='enum' href='sota/datatype/url/enum.Method.html' title='sota::datatype::url::Method'>Method</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
