# Site title and subtitle. This is used in _includes/header.html
title: 'GENIVI SOTA Project'
subtitle: 'Software Updates Over the Air'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-69301419-1'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/genivi/rvi_sota_server'

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Getting Started'],
    ['dev', 'Developers'],
    ['cli', 'Client Documentation'],
    ['ref', 'Reference']
    #['post', 'Posts']
]

# This creates navigation tabs. First element in the array is the name of the tab,
# second is the id of the tab's div, third is the list of sections that should
# appear in the tab
# 
# Note that any sections which aren't assigned to any navigation tab will not show 
# up in navigation anywhere
navigation_tabs: [
    ['GENIVI SOTA', 'genivi', ['doc', 'dev', 'cli', 'ref']]
]

header_links: [
    ['Server src (stable)', 'https://github.com/genivi/rvi_sota_server'],
    ['Server src (dev)', 'https://github.com/advancedtelematic/rvi_sota_server'],
    ['Client src (stable)', 'https://github.com/genivi/rvi_sota_client'],
    ['Client src (dev)', 'https://github.com/advancedtelematic/rvi_sota_client'],
    ['Docs', 'http://advancedtelematic.github.io/rvi_sota_server/']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/rvi_sota_server' 

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md','Gemfile*','Makefile','Dockerfile']

gems: 
  - jekyll-asciidoc

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style


