version: '2'
services:

  mysql:
    image: advancedtelematic/mariadb:stable
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: "sota-test"
      MYSQL_USER: "sota"
      MYSQL_PASSWORD: "s0ta"
      MYSQL_DATABASES: "sota_resolver sota_resolver_test sota_resolver% sota_core sota_core_test sota_core% sota_device_registry% sota_device_registry sota_device_registry_test"
    command: ["--character-set-server=utf8", "--collation-server=utf8_unicode_ci", "--max-connections=1000"]

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "DeviceSeen-sota,PackageCreated-sota"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  device-registry:
    image: advancedtelematic/sota-device_registry
    ports:
     - 8083:8083
    expose:
     - 8083
    depends_on:
      - mysql
      - kafka
    environment:
     BIND_HOST: 0.0.0.0
     DEVICE_REGISTRY_DB_URL: "jdbc:mariadb://mysql:3306/sota_device_registry"
     DB_MIGRATE: 'true'
     KAFKA_HOST: "kafka:9092"
     KAFKA_TOPIC_SUFFIX: "sota"
     MESSAGING_MODE: "kafka"
     DB_ALIVE_URL: "mysql:3306"
     AUTH_PROTOCOL: "none"

  resolver:
    image: advancedtelematic/sota-resolver
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
      - mysql
      - kafka
      - device-registry
    environment:
      BIND_HOST: 0.0.0.0
      RESOLVER_DB_URL: "jdbc:mariadb://mysql:3306/sota_resolver"
      DB_MIGRATE: 'true'
      DEVICE_REGISTRY_HOST: "device-registry"
      DEVICE_REGISTRY_PORT: "8083"
      KAFKA_HOST: "kafka:9092"
      KAFKA_TOPIC_SUFFIX: "sota"
      MESSAGING_MODE: "kafka"
      PACKAGES_VERSION_FORMAT: ".+"
      DB_ALIVE_URL: "mysql:3306"
      AUTH_PROTOCOL: "none"

  core:
    image: advancedtelematic/sota-core
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
      - kafka
      - device-registry
      - resolver
    environment:
      BIND_HOST: 0.0.0.0
      CORE_DB_URL: "jdbc:mariadb://mysql:3306/sota_core"
      CORE_INTERACTION_PROTOCOL: 'none'
      DB_ALIVE_URL: "mysql:3306"
      DB_MIGRATE: 'true'
      DEVICE_REGISTRY_HOST: "device-registry"
      DEVICE_REGISTRY_PORT: "8083"
      KAFKA_HOST: 'kafka:9092'
      KAFKA_TOPIC_SUFFIX: 'sota'
      MESSAGING_MODE: 'kafka'
      SOTA_RESOLVER_HOST: "resolver"
      SOTA_RESOLVER_PORT: "8081"
      PACKAGES_VERSION_FORMAT: ".+"
      AUTH_PROTOCOL: "none"

  ldapserver:
    image: advancedtelematic/openldap:genivi
    ports:
      - 9389:389
    command: "--loglevel debug"

  webserver:
    image: advancedtelematic/sota-webserver
    depends_on:
      - device-registry
      - kafka
      - resolver
      - core
      - ldapserver
    ports:
      - 9000:9000
    expose:
      - 9000
    environment:
      KAFKA_HOST: "kafka:9092"
      KAFKA_TOPIC_SUFFIX: "sota"
      MESSAGING_MODE: "kafka"
      PLAY_CRYPTO_SECRET: "YM5B6o<ywKn4tTyA;tOZ<2xUEajF4DDi=O/PPm1Q^w2LqtKISd9oqYT6b>>C1gQa"
      DEVICE_REGISTRY_HOST: "device-registry"
      DEVICE_REGISTRY_PORT: "8083"
      SOTA_CORE_HOST: "core"
      SOTA_CORE_PORT: "8080"
      SOTA_RESOLVER_HOST: "resolver"
      SOTA_RESOLVER_PORT: "8081"
      LDAP_HOST: "ldapserver"
      LDAP_PORT: "389"
      LDAP_AUTHN_ID: "cn=admin,dc=genivi,dc=org"
      LDAP_PASSWORD: "admin"
